/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package market.app.client.ui;

import entity.Account;
import entity.Order;
import entity.OrderDetail;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import market.app.client.Config;
import market.app.client.connect.ConnectServer;
import service.IOrderDetailService;
import service.IOrderService;

/**
 *
 * @author Le Tuan
 */
public class frmOrder extends javax.swing.JFrame {

    private List<OrderDetail> _details;
    private Account _account;
    private boolean _status;

    private IOrderService orderService = ConnectServer.getInstance().getOrderService();
    private Date now = new Date();
    /**
     * Creates new form frmOrder
     */
    private final DefaultTableModel modelTableOrderDetail = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
        }
    };
    private final String[] colums = new String[]{"STT", "Tên hàng", "Đơn vị tính", "Đơn giá" ,"Số lượng", "Thành tiền"};

    public frmOrder(List<OrderDetail> details, Account account, boolean status) {
        initComponents();
        Config.initColTable(tblOrderDetail4, modelTableOrderDetail, colums);

        setLocationRelativeTo(null);
        //form sale send
        _details = details;
        _account = account;
        _status = status;

        lblOrderNumber.setText("HĐ số: " + (getNumberOrder() + 1) + "");
        lblDateTime.setText("Ngày: " + Config.converDateToString(now));
        lblStaffName.setText("Bán hàng: " + _account.getStaff().getName());
        btnPaySuccess.setEnabled(false);
        Config.loadOrderDetailToList(modelTableOrderDetail, _details);
        lblTotalMoney.setText(Config.formatMoney(Config.calTotalMoneyByListOrderDetail(_details)));

    }

    public frmOrder(Order order) {
        initComponents();
        Config.initColTable(tblOrderDetail4, modelTableOrderDetail, colums);

        setLocationRelativeTo(null);

        Config.loadOrderDetailToList(modelTableOrderDetail, order.getDetails());
        lblTotalMoney.setText(Config.formatMoney(Config.calTotalMoneyByListOrderDetail(_details)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMarketName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblOrderNumber = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        lblStaffName = new javax.swing.JLabel();
        pnOrderDetailInOrder = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblOrderDetail4 = new javax.swing.JTable();
        lblTagTotalMoney = new javax.swing.JLabel();
        lblTotalMoney = new javax.swing.JLabel();
        lblThanks = new javax.swing.JLabel();
        btnPaySuccess = new javax.swing.JButton();
        btnPrintOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblMarketName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMarketName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarketName.setText("Siêu thị Kmart");

        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddress.setText("22 Nguyễn Văn Bảo, Q. Gò Vấp,  TP. HCM");

        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoneNumber.setText("ĐT: 0343237897");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Hóa Đơn Bán Lẻ");

        lblOrderNumber.setText("Số: HD00001");

        lblDateTime.setText("Ngày: 25-08-2022 18:00:00");

        lblStaffName.setText("Bán hàng: Lê Tuấn");

        pnOrderDetailInOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 123, 157), 3, true), "Danh sách mặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblOrderDetail4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblOrderDetail4);

        lblTagTotalMoney.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTagTotalMoney.setText("Tổng tiền:");

        lblTotalMoney.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalMoney.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalMoney.setText("0,000 VNÐ");

        javax.swing.GroupLayout pnOrderDetailInOrderLayout = new javax.swing.GroupLayout(pnOrderDetailInOrder);
        pnOrderDetailInOrder.setLayout(pnOrderDetailInOrderLayout);
        pnOrderDetailInOrderLayout.setHorizontalGroup(
            pnOrderDetailInOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrderDetailInOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOrderDetailInOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(pnOrderDetailInOrderLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTagTotalMoney)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnOrderDetailInOrderLayout.setVerticalGroup(
            pnOrderDetailInOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOrderDetailInOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnOrderDetailInOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalMoney)
                    .addComponent(lblTagTotalMoney))
                .addGap(10, 10, 10))
        );

        lblThanks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblThanks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThanks.setText("Cảm ơn Quý Khách!");

        btnPaySuccess.setBackground(new java.awt.Color(69, 123, 157));
        btnPaySuccess.setForeground(new java.awt.Color(255, 255, 255));
        btnPaySuccess.setText("Hoàn tất thanh toán");
        btnPaySuccess.setToolTipText("Lưu hóa đơn");
        btnPaySuccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaySuccessActionPerformed(evt);
            }
        });

        btnPrintOrder.setBackground(new java.awt.Color(29, 146, 183));
        btnPrintOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintOrder.setText("In hóa đơn");
        btnPrintOrder.setToolTipText("In hóa đơn gửi cho khách hàng kiểm tra");
        btnPrintOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnOrderDetailInOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblThanks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblMarketName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPaySuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrintOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblMarketName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhoneNumber)
                .addGap(42, 42, 42)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderNumber)
                    .addComponent(lblDateTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStaffName)
                .addGap(18, 18, 18)
                .addComponent(pnOrderDetailInOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblThanks)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaySuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrintOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int getNumberOrder() {

        try {
            int countOrder = orderService.getAllOrder().size();
            return countOrder;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi lấy số hóa đơn!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        return -1;
    }

    private void updateOrderIdAndInsertOrderDetail(List<OrderDetail> details, Order orderFinded) {
        try {
            IOrderDetailService orderDetailService = ConnectServer.getInstance().getOrderDetailService();
            details.forEach(detail -> {
                detail.setOrder(orderFinded);
                try {
                    orderDetailService.addOrUpdateOrderDetail(detail);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Lỗi thêm chi tiết hóa đơn!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            });
            JOptionPane.showMessageDialog(null, "Bạn đã hoàn thành thanh toán cho hóa đơn này!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi thêm cập nhật chi tiết hóa đơn", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnPaySuccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaySuccessActionPerformed
        try {
            Order _order = new Order(now, _account.getStaff());
            int orderId = orderService.addOrUpdateOrder(_order);
            Order orderFinded = orderService.findOrderById(orderId);
            updateOrderIdAndInsertOrderDetail(_details, orderFinded);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi thêm hóa đơn", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPaySuccessActionPerformed

    private void btnPrintOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintOrderActionPerformed
        // TODO add your handling code here:
        boolean print = Config.printOrder(now, _details, getNumberOrder(), _account.getStaff().getName());
        if(print && _status){
            btnPaySuccess.setEnabled(true);
        }
    }//GEN-LAST:event_btnPrintOrderActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmOrder().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaySuccess;
    private javax.swing.JButton btnPrintOrder;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblMarketName;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblStaffName;
    private javax.swing.JLabel lblTagTotalMoney;
    private javax.swing.JLabel lblThanks;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalMoney;
    private javax.swing.JPanel pnOrderDetailInOrder;
    private javax.swing.JTable tblOrderDetail4;
    // End of variables declaration//GEN-END:variables
}
