/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package market.app.client.ui;

import entity.Account;
import entity.Staff;
import market.app.client.Config;

/**
 *
 * @author Le Tuan
 */
public class frmViewInfor extends javax.swing.JInternalFrame {

    private Account _account;

    /**
     * Creates new form frmViewInfor
     * @param account
     */
    public frmViewInfor(Account account) {
        initComponents();
        Config.hideTitleBarInternalFrame(this);

        _account = account;
        loadUserInfoToInput(_account);
    }

    private void loadUserInfoToInput(Account account) {
        //cancel event edit text
        txtStaffID.setEditable(false);
        txtGender.setEditable(false);
        txtAddress.setEditable(false);
        txtPhoneNumber.setEditable(false);
        txtPosition.setEditable(false);
        txtStaffIdentification.setEditable(false);
        txtStaffName.setEditable(false);
        txtSalary.setEditable(false);

        //load info
        Staff staff = account.getStaff();
        txtStaffID.setText(staff.getId());
        txtGender.setText(staff.isGender() == false ? "Nữ" : "Nam");
        txtAddress.setText(staff.getAddress());
        txtPhoneNumber.setText(staff.getPhone());
        txtPosition.setText(!staff.isPosition() ? "Nhân viên bán hàng" : "Quản lý");
        txtSalary.setText(staff.isPosition() ? "10.000.000 VNĐ" :  "7.000.000 VNĐ");
        txtStaffIdentification.setText(staff.getIdentify());
        txtStaffName.setText(staff.getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnViewInfor = new javax.swing.JPanel();
        lblStaffID = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JTextField();
        lblStaffName = new javax.swing.JLabel();
        txtStaffName = new javax.swing.JTextField();
        lblStaffIdentification = new javax.swing.JLabel();
        txtStaffIdentification = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblPosition = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        lblSalary = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        btnPasswordChange = new javax.swing.JButton();

        pnViewInfor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 123, 157), 3, true), "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblStaffID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffID.setText("Mã nhân viên: ");

        txtStaffID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblStaffName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffName.setText("Tên nhân viên: ");

        txtStaffName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblStaffIdentification.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffIdentification.setText("CMND/CCCD:");

        txtStaffIdentification.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhoneNumber.setText("Số điện thoại:");

        txtPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAddress.setText("Địa chỉ: ");

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGender.setText("Giới tính: ");

        txtGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPosition.setText("Chức vụ: ");

        txtPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSalary.setText("Mức lương: ");

        txtSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnViewInforLayout = new javax.swing.GroupLayout(pnViewInfor);
        pnViewInfor.setLayout(pnViewInforLayout);
        pnViewInforLayout.setHorizontalGroup(
            pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnViewInforLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStaffID)
                    .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender))
                .addGap(18, 18, 18)
                .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnViewInforLayout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnViewInforLayout.createSequentialGroup()
                        .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnViewInforLayout.createSequentialGroup()
                                .addComponent(lblStaffName)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtStaffName))
                        .addGap(18, 18, 18)
                        .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStaffIdentification)
                            .addComponent(txtStaffIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnViewInforLayout.createSequentialGroup()
                        .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPosition))
                        .addGap(18, 18, 18)
                        .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnViewInforLayout.createSequentialGroup()
                                .addComponent(lblSalary)
                                .addGap(0, 186, Short.MAX_VALUE))
                            .addComponent(txtSalary)))
                    .addComponent(txtAddress))
                .addContainerGap())
        );
        pnViewInforLayout.setVerticalGroup(
            pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnViewInforLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStaffID)
                    .addComponent(lblStaffName)
                    .addComponent(lblStaffIdentification))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStaffIdentification, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtStaffName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStaffID))
                .addGap(35, 35, 35)
                .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtAddress))
                .addGap(31, 31, 31)
                .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(lblPosition)
                    .addComponent(lblSalary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnViewInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtGender, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtPosition))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnPasswordChange.setBackground(new java.awt.Color(69, 123, 157));
        btnPasswordChange.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPasswordChange.setForeground(new java.awt.Color(255, 255, 255));
        btnPasswordChange.setText("Đổi mật khẩu");
        btnPasswordChange.setToolTipText("Chọn để đổi mật khẩu");
        btnPasswordChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnViewInfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPasswordChange, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPasswordChange, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(pnViewInfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasswordChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordChangeActionPerformed
        // TODO add your handling code here:
        new frmPasswordChange(_account).setVisible(true);
    }//GEN-LAST:event_btnPasswordChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPasswordChange;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblStaffID;
    private javax.swing.JLabel lblStaffIdentification;
    private javax.swing.JLabel lblStaffName;
    private javax.swing.JPanel pnViewInfor;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtStaffID;
    private javax.swing.JTextField txtStaffIdentification;
    private javax.swing.JTextField txtStaffName;
    // End of variables declaration//GEN-END:variables
}
